### ISSUE TITLE
Remove `into_inner`

### ISSUE THREAD

**Issue by oberien** [oberien/rust-aes-stream#5]
While that makes sense for `BufReader` and `BufWriter`, it doesn't make sense to write encrypted and unencrypted data into a file / read both from it. For the in-memory case pass `&mut Vec` (i.e. `vec.by_ref()`).

**Comment by rkuhn** [comment]
FYI: I just found myself reimplementing this method for the in-memory case:

```rust
impl<E: BlockEncryptor> EncryptWrite for AesWriter<E, Vec<u8>> {
    fn finalise(mut self) -> Result<Vec<u8>> {
        self.flush()?;
        Ok(self.writer.take().unwrap())
    }
}
```

This method makes in-memory use safer and more concise, so I’m wondering whether something like this shouldn’t be reinstated.

**Comment by oberien** [comment]
Is there a reason you pass ownership over the whole `Vec` instead of just passing a mutable reference to is as shown [in the second example of AesWriter](https://docs.rs/aes-stream/0.2.1/aesstream/struct.AesWriter.html)?

```rust
let key: [u8; 16] = OsRng::new()?.gen();
let encryptor = AesSafe128Encryptor::new(&key);
let mut encrypted = Vec::new();
{
    let mut writer = AesWriter::new(&mut encrypted, encryptor)?;
    writer.write_all("Hello World!".as_bytes())?;
}
```

Borrowing it mutably allows you to just reuse the Vec directly once the writer is dropped.

**Comment by rkuhn** [comment]
Yes, that’s true. What I’m writing is an API (internal at the moment) that manages keys and encryption schemes and gives the user an experience like

```rust
let mut writer = key_store.encrypt(public_key);
writer.write(...);
...
let ciphertext = writer.finalise();
```

This makes it very obvious how to use the stream writer, but you’re right in that it doesn’t really offer any extra safety over

```rust
let mut ciphertext = Vec::new();
let mut writer = key_store.encrypt(public_key, &mut ciphertext);
writer.write(...);
...
drop(writer);
```

The last line is not so nice because the user needs to know this magical Rust “trick”, but it does work. And it offers the flexility of writing directly to a File etc. Okay, you convinced me :-)

**Comment by oberien** [comment]
FYI this project is pretty much unmaintained and hasn't been updated in 4 years (as I don't have a personal use for it anymore). It still depends on the old [DaGenix/rust-crypto](https://github.com/DaGenix/rust-crypto) library instead of the newer [RustCrypto](https://github.com/RustCrypto) project implementations. To the best of my knowledge, this crate should still be fine, but I can't vouch for it. Additionally, for your use-case you probably want to use an authenticated encryption algorithm like chacha20-poly1305 or AES-GCM instead of AES-CBC which this library uses under the hood.

This crate was primarily meant to provide an easy cryptographic interface over `io::{Write, Read, Seek}` to be used by a later project of mine which never materialized. Especially the `Seek` requirement made using CBC the easiest solution back then.
